#ifndef ADVENTOFCODE2021_INPUT_SOURCE_HPP
#define ADVENTOFCODE2021_INPUT_SOURCE_HPP

#include <fstream>

#if TEST_RUN
    static std::ifstream cin(INPUT_SOURCE_FILE_NAME);
#endif

#endif //ADVENTOFCODE2021_INPUT_SOURCE_HPP