#ifndef ADVENTOFCODE2021_BASE_INCLUDES_H
#define ADVENTOFCODE2021_BASE_INCLUDES_H

#include <iostream>
#include <iterator>
#include <ranges>
#include <vector>
#include <bitset>
#include <list>
#include <chrono>
#include <unordered_map>
#include <map>
#include <set>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <sstream>
#include <stack>
#include <unordered_set>
#include <atomic>
#include <thread>
#include <execution>
#include <span>
#include <regex>
#include "../input_source.hpp"
#include "word_delimited_by.h"
#include "get_line_stream.h"
#include "std_extentions.hpp"
#include "extended_binary_operations.hpp"
#include "time_extensions.hpp"
#include "point.hpp"
#include "hash_tools.hpp"
#include "compile_time_math.hpp"
#include "efficient_stack.hpp"
#include "str_number.hpp"
#include "math.hpp"
#include "aaa_to_zzz_string.hpp"
#include "matrix.hpp"
#include "binary_tools.hpp"

#endif